# fly.toml app configuration file generated for team3-project-2-app on 2025-09-09T17:53:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'team3-project-2-app'
primary_region = 'sjc'
console_command = '/code/manage.py shell'

[build]

# [deploy]
  # release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/staticfiles'
  url_prefix = '/static/'


[[http_service.checks]]
  interval = "15s"
  timeout = "10s"
  method = "GET"
  path = "/health/"
  grace_period = "30s"
