# Generated by Django 4.2.23 on 2025-08-13 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CafeIf",
            new_name="CafeId",
        ),
    ]
