# Generated by Django 4.2.23 on 2025-08-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0003_cafeid_franchise_cafeid_franchise_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cafesales',
            name='cafes_cafes_cafe_id_18d008_idx',
        ),
        migrations.RemoveField(
            model_name='cafesales',
            name='date',
        ),
        migrations.AddField(
            model_name='cafesales',
            name='month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafesales',
            name='year',
            field=models.PositiveIntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cafesales',
            index=models.Index(fields=['cafe', 'year', 'month'], name='cafes_cafes_cafe_id_7a119f_idx'),
        ),
    ]
