# Generated by Django 4.2.23 on 2025-08-18 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cafes", "0005_remove_cafesales_aov_cafeid_city_cafeid_district"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cafeid",
            old_name="district",
            new_name="distinct",
        ),
    ]
