# Generated by Django 4.2.23 on 2025-08-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafes", "0006_rename_district_cafeid_distinct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafeid",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cafeid",
            name="distinct",
            field=models.CharField(max_length=100),
        ),
    ]
