# Generated by Django 4.2.23 on 2025-08-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafes", "0008_alter_cafeid_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafesales",
            name="month",
            field=models.CharField(max_length=2),
        ),
    ]
