# Generated by Django 4.2.23 on 2025-08-18 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0010_cafesales_unique_cafe_year_month'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cafesales',
            name='unique_cafe_year_month',
        ),
        migrations.RemoveIndex(
            model_name='cafesales',
            name='cafes_cafes_cafe_id_7a119f_idx',
        ),
        migrations.RemoveField(
            model_name='cafesales',
            name='month',
        ),
        migrations.RemoveField(
            model_name='cafesales',
            name='year',
        ),
        migrations.AddField(
            model_name='cafesales',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='cafesales',
            index=models.Index(fields=['cafe', 'date'], name='cafes_cafes_cafe_id_18d008_idx'),
        ),
        migrations.AddConstraint(
            model_name='cafesales',
            constraint=models.UniqueConstraint(fields=('cafe', 'date'), name='unique_cafe_date'),
        ),
    ]
