# Generated by Django 4.2.23 on 2025-08-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0011_remove_cafesales_unique_cafe_year_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafesales',
            name='date',
            field=models.CharField(help_text='YYYY-MM 형식으로 입력 (예: 2025-07)', max_length=7),
        ),
    ]
